FROM roverwolf/centos7

MAINTAINER test@docker.com

RUN rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm && yum install nginx -y $$ yum clean all

EXPOSE 80

VOLUME  ["/etc/nginx", "/var/log/nginx"]

CMD ["/usr/sbin/nginx", "-c", "/etc/nginx/nginx.conf"]